# Generated by Django 5.0.2 on 2024-02-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomManager', '0002_roommanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommanager',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
