# Generated by Django 5.0.2 on 2024-02-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RoomManager', '0003_alter_roommanager_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommanager',
            name='date',
            field=models.DateField(),
        ),
    ]
