# Generated by Django 5.0.2 on 2024-02-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RoomManager', '0004_alter_roommanager_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roommanager',
            options={'ordering': ('date',)},
        ),
        migrations.AlterUniqueTogether(
            name='roommanager',
            unique_together={('room_id', 'date')},
        ),
    ]
